# Generated by Django 4.1.7 on 2023-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
