# Generated by Django 4.1.7 on 2023-03-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_friend_nickname_alter_friend_friend_delete_frnick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='2945973d7c1f6e9c', max_length=20),
        ),
    ]
