# Generated by Django 4.1.7 on 2023-03-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_friend_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='edced46098b7d817', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token1',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
