# Generated by Django 4.1.7 on 2023-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_friend_nickname_alter_profile_token1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='c377040192705c25', max_length=20),
        ),
    ]
