# Generated by Django 4.1.7 on 2023-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_friend_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='a6ded1c38d3ae5f8', max_length=20),
        ),
    ]
