# Generated by Django 4.1.7 on 2023-03-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_friend_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='d121b4ea036ae694', max_length=20),
        ),
    ]
