# Generated by Django 4.1.7 on 2023-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_friend_nickname_alter_profile_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='72943083', max_length=8),
        ),
    ]
