# Generated by Django 4.1.7 on 2023-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_friend_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='nickname',
            field=models.CharField(default='3b0a855b', max_length=8),
        ),
    ]
