# Generated by Django 4.1.7 on 2023-03-15 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='room',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='second_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='room', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='room_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
